version: '3.7'

services:
  django:
    container_name: pharmacy_site
    build:
      context: .
      dockerfile: Dockerfile
    image: pharmacy_docker
    stdin_open: true
    tty: true
    volumes:
    - .:/var/www/pharmacy
    ports:
    - "8000:8000"
