# Generated by Django 2.1.7 on 2020-05-16 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_cart_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='UserName', max_length=100)),
                ('surname', models.CharField(help_text='UserSurname', max_length=100)),
                ('telephone_number', models.CharField(help_text='UserTelephone', max_length=100)),
                ('email', models.CharField(help_text='UserEmail', max_length=100)),
                ('perms', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
